/* TEXTOS — GENERADO. No editar: se escribe desde textos.json. */
var LANG = "es";
var T = {
  "ver": "Ver ↗",
  "verYoutube": "Ver en YouTube ↗",
  "pack": "Pack",
  "packTit": "Los proyectos completos",
  "packSub": "Todos completos, en vez de {antes}",
  "comprar": "Comprar ↗",
  "gratis": "Gratis",
  "gratisSub": "Sonidos de progressive house para empezar",
  "descargar": "Descargar ↗",
  "contactoTit": "¿Alguna duda antes de comprar?",
  "contactoNota": "Pregunta lo que quieras. Contesto yo, no un formulario.",
  "proyecto": "Proyecto",
  "previaTit": "Míralo por dentro antes de descargar",
  "previaSub": "Abro esta sesión y te enseño cómo está montada",
  "oirAria": "Escuchar el fragmento",
  "oirPie": "Así suena la sesión terminada",
  "bpm": "BPM",
  "tono": "Tonalidad",
  "pistas": "Pistas",
  "enGrupos": " en {n} grupos",
  "formato": "Proyecto de Live",
  "formatoSolo": "Archivo .als · Proyecto de Ableton Live",
  "d1t": "El arreglo completo.",
  "d1": "De la intro al último compás, con las pistas nombradas y agrupadas tal y como las tengo yo.",
  "d2t": "Todos los racks y cadenas de efectos.",
  "d2": "Cada dispositivo en su orden y con sus ajustes. Desactiva uno y oye qué aportaba.",
  "d3t": "Todas las automatizaciones.",
  "d3": "Filtros, envíos y volúmenes, en su sitio — la mitad de por qué el tema respira.",
  "d4t": "El MIDI de cada parte.",
  "d4": "Cambia las notas y ya es tuyo.",
  "conseguir": "Conseguir el proyecto",
  "compraNota": "Descarga inmediata. Pago seguro gestionado por Gumroad.",
  "legal": "Es mi propia recreación, hecha de oído. No contiene audio, samples ni material del lanzamiento original. Puedes publicar lo que hagas con ella; no puedes revender ni redistribuir el archivo del proyecto.",
  "hechoTit": "Con qué está hecho",
  "hechoSub": "El {pct}&nbsp;% de las cadenas son dispositivos que Live ya trae puestos. Lo demás son plugins de terceros — y aquí tienes cuáles, por si no los tienes.",
  "hechoSerie": "Esto ya lo tienes · de serie en Live",
  "hechoTerceros": "De terceros",
  "hechoMas": "y {n} más",
  "hechoPie": "Si te falta alguno, el proyecto se abre igual y Live solo marca ese dispositivo: el arreglo, el MIDI y las automatizaciones siguen en su sitio.",
  "esGratuito": "Es gratuito",
  "sinEquivalente": "Sin equivalente gratuito",
  "prefijoGratis": "Gratis: ",
  "prefijoSust": "En su lugar: ",
  "ldName": "{t} — Proyecto completo de Ableton Live",
  "ldDesc": "Mi recreación de «{t}» de {a} como sesión de Ableton Live: el arreglo completo, los racks y la automatización.",
  "midiTit": "El MIDI, gratis",
  "midiSub": "{que} de este tema, tal y como salen de la sesión. Sin pagar nada.",
  "midiBoton": "Descargar el MIDI ↗",
  "midiTag": "+ MIDI gratis",
  "oirCorto": "Escuchar un fragmento",
  "fichaEnlace": "Ver la ficha completa de este proyecto ↗"
};
