/* TEXTOS — GENERADO. No editar: se escribe desde textos.json. */
var LANG = "en";
var T = {
  "ver": "View ↗",
  "verYoutube": "Watch on YouTube ↗",
  "pack": "Bundle",
  "packTit": "All the projects",
  "packSub": "Every one of them, instead of {antes}",
  "comprar": "Buy ↗",
  "gratis": "Free",
  "gratisSub": "Progressive house sounds to get you started",
  "descargar": "Download ↗",
  "contactoTit": "Anything you want to ask before buying?",
  "contactoNota": "Ask me anything. You get me, not a form.",
  "proyecto": "Project",
  "previaTit": "See inside before you download",
  "previaSub": "I open this session and show you how it's put together",
  "oirAria": "Play the clip",
  "oirPie": "This is how the finished session sounds",
  "bpm": "BPM",
  "tono": "Key",
  "pistas": "Tracks",
  "enGrupos": " in {n} groups",
  "formato": "Live project",
  "formatoSolo": ".als file · Ableton Live project",
  "d1t": "The full arrangement.",
  "d1": "From the intro to the last bar, with the tracks named and grouped exactly as I keep them.",
  "d2t": "Every rack and effect chain.",
  "d2": "Every device in order and with its settings. Switch one off and hear what it was doing.",
  "d3t": "All the automation.",
  "d3": "Filters, sends and volumes, all in place — half the reason the track breathes.",
  "d4t": "The MIDI for every part.",
  "d4": "Change the notes and it's yours.",
  "conseguir": "Get the project",
  "compraNota": "Instant download. Secure payment handled by Gumroad.",
  "legal": "This is my own recreation, made by ear. It contains no audio, samples or material from the original release. You can publish whatever you make with it; you can't resell or redistribute the project file.",
  "hechoTit": "What it's built with",
  "hechoSub": "{pct}&nbsp;% of the chains are devices Live already ships with. The rest are third-party plugins — and here's which, in case you don't have them.",
  "hechoSerie": "You already have these · stock in Live",
  "hechoTerceros": "Third-party",
  "hechoMas": "and {n} more",
  "hechoPie": "If you're missing one, the project still opens and Live just flags that device: the arrangement, the MIDI and the automation stay where they are.",
  "esGratuito": "It's free",
  "sinEquivalente": "No free equivalent",
  "prefijoGratis": "Free: ",
  "prefijoSust": "Instead: ",
  "ldName": "{t} — Complete Ableton Live project",
  "ldDesc": "My recreation of “{t}” by {a} as an Ableton Live session: the full arrangement, the racks and the automation.",
  "midiTit": "The MIDI, free",
  "midiSub": "{que} from this track, straight out of the session. No payment.",
  "midiBoton": "Download the MIDI ↗",
  "midiTag": "+ Free MIDI",
  "oirCorto": "Play a clip",
  "fichaEnlace": "See the full page for this project ↗"
};
